[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Git Gateway for Decap CMS
[[plugins]]
  package = "netlify-plugin-git-gateway" 